### PR TITLE
Changed default m_component value to -1 in FieldSpecificationBase to …

### LINKED ISSUE #1494: Set default value of component to -1 in field specifications.
**Describe the bug**
Default for setting a field should be to set all values, not just the first dimension.

- [x] Change the default value of component
- [ ] Run integrated tests to check for rebaselines.

### PR DESCRIPTION
**Pull request by jafranc**
This resolves #1494 
in setting default value for `m_component` in _FieldSpecificationBase_ class to *-1* so that calling 

https://github.com/GEOSX/GEOSX/blob/04ef94451691bb34c65b9fc8f0131000fea25ccd/src/coreComponents/common/FieldSpecificationOps.hpp#L181-L187

through `FieldSpecificationBase::applyFieldValueKernel`  will requires by default that all component are initialized to the passed `value` (instead of only the first)
https://github.com/GEOSX/GEOSX/blob/04ef94451691bb34c65b9fc8f0131000fea25ccd/src/coreComponents/common/FieldSpecificationOps.hpp#L189-L199

### CODE REVIEW

**Review by klevzoff — APPROVED** [review]
Assuming the integrated tests pass, this is good to go! But I suspect a few rebaselines may be needed just because of this single value change in the restart file

**Comment by jafranc** [comment]
Indeed, restart checks failed with:  

```
Rank 0 is comparing /home/jfranc/code/cxx/GEOSX/integratedTests/update/run/wellboreMesh/OpenWellbore_01/0to3_restart_000000003/rank_0000000.hdf5 with /home/jfranc/code/cxx/GEOSX/integratedTests/update/run/wellboreMesh/baselines/OpenWellbore_01/0to3_restart_000000003/rank_0000000.hdf5 
********************************************************************************
Error: /Problem/FieldSpecifications/innerPressure/component/__values__
        Scalar values of types int32 and int32 differ: -1, 0.
******************************************************************************** 
```
But I have failure to converge in some tests:

- PhaseFieldFracture_DamageOnly_01_1_geosx
- PhaseFieldFracture_DamageAndLoad_01_1_geosx
- compressible_1d_01_1_geosx
- compressible_2d_2fluids_01_1_geosx
- compressible_2d_2fluids_hybrid_01_1_geosx
- sourceFlux_2d_01_1_geosx
- Sneddon_conforming01_1_geosx
- fractureMatrixFlow_Embedded2d_01_1_geosx
- poroElastic_embFractures_01_1_geosx

**Comment by jafranc** [comment]
The line responsible is there:
https://github.com/GEOSX/GEOSX/blob/71c5fa8023907886064edf613e345105693dc6fa/src/coreComponents/fieldSpecification/FieldSpecificationBase.hpp#L651-L664

later messing the dof indexes:
https://github.com/GEOSX/GEOSX/blob/71c5fa8023907886064edf613e345105693dc6fa/src/coreComponents/fieldSpecification/FieldSpecificationBase.hpp#L715-L728

**Comment by klevzoff** [comment]
> should we safe-guard it also ?

Yes, please do. Good spot!

**Comment by jafranc** [comment]
Preparing the rebaseline PR, I did have the multi-core restart checks _ZeroViscosity_06_2_restartcheck_ failing for an unanticipated reason. Here is extract from the logs :
<details>
 <summary> 0008.python_KGD_ZeroViscosity_06_KGD_ZeroViscosity_06_2_restartcheck_.log</summary>

 ```
#ATS: commandLine = /usr/bin/mpirun -n 6 --oversubscribe /usr/bin/python -m mpi4py /home/jfranc/code/cxx/GEOSX/integratedTests/geosxats/helpers/restartcheck.py -a 0.0002 -r 1e-07 -w /home/jfranc/code/cxx
/GEOSX/integratedTests/update/run/HydrofracturingSolver/KGD_ZeroViscosity_06/KGD_ZeroViscosity_restart_[0-9]+\.root /home/jfranc/code/cxx/GEOSX/integratedTests/update/run/HydrofracturingSolver/baselines/
KGD_ZeroViscosity_06/KGD_ZeroViscosity_restart_[0-9]+\.root
#ATS: directory = /home/jfranc/code/cxx/GEOSX/integratedTests/update/run/HydrofracturingSolver
#ATS: executable = /usr/bin/python -m mpi4py
#ATS: name = python(KGD_ZeroViscosity_06/KGD_ZeroViscosity_06_2_restartcheck)
#ATS: clas = ['/home/jfranc/code/cxx/GEOSX/integratedTests/geosxats/helpers/restartcheck.py', '-a', '0.0002', '-r', '1e-07', '-w', '/home/jfranc/code/cxx/GEOSX/integratedTests/update/run/HydrofracturingS
olver/KGD_ZeroViscosity_06/KGD_ZeroViscosity_restart_[0-9]+\\.root', '/home/jfranc/code/cxx/GEOSX/integratedTests/update/run/HydrofracturingSolver/baselines/KGD_ZeroViscosity_06/KGD_ZeroViscosity_restart
_[0-9]+\\.root']
#ATS: np = 6
#ATS: script = 
#ATS: testpath =  
Rank 0 is comparing /home/jfranc/code/cxx/GEOSX/integratedTests/update/run/HydrofracturingSolver/KGD_ZeroViscosity_06/KGD_ZeroViscosity_restart_000000023/rank_0000000.hdf5 with /home/jfranc/code/cxx/GEOS
X/integratedTests/update/run/HydrofracturingSolver/baselines/KGD_ZeroViscosity_06/KGD_ZeroViscosity_restart_000000023/rank_0000000.hdf5 
********************************************************************************
Error: /Problem/FieldSpecifications/frac/component/__values__
	Scalar values of types int32 and int32 differ: -1, 0.
********************************************************************************
********************************************************************************
Error: /Problem/FieldSpecifications/waterDensity/component/__values__
	Scalar values of types int32 and int32 differ: -1, 0.
********************************************************************************
********************************************************************************
Error: /Problem/FieldSpecifications/separableFace/component/__values__
	Scalar values of types int32 and int32 differ: -1, 0.
********************************************************************************
********************************************************************************
Error: /Problem/FieldSpecifications/sourceTerm/component/__values__
	Scalar values of types int32 and int32 differ: -1, 0.
********************************************************************************
The files are different.

Rank 3 is comparing /home/jfranc/code/cxx/GEOSX/integratedTests/update/run/HydrofracturingSolver/KGD_ZeroViscosity_06/KGD_ZeroViscosity_restart_000000023/rank_0000003.hdf5 with /home/jfranc/code/cxx/GEOS
X/integratedTests/update/run/HydrofracturingSolver/baselines/KGD_ZeroViscosity_06/KGD_ZeroViscosity_restart_000000023/rank_0000003.hdf5 
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/FaceManager/edgeList/__values__
	Arrays of types int8 and int8 have 9560 values of which 7 have differing values.
	Statistics of the differences greater than 0:
		max_index = (2544,), max = 2, mean = 1.4285714285714286, std = 0.4948716593053935
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/nodeManager/edgeList/__values__
	Arrays of types int8 and int8 have 7720 values of which 6 have differing values.
	Statistics of the differences greater than 0:
		max_index = (6072,), max = 1, mean = 1.0, std = 0.0
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/neighborData/1/ghostsToReceive
	Arrays of types int64 and int64 have 11 values of which 2 have differing values.
	Statistics of the differences greater than 0:
		max_index = (8,), max = 1, mean = 1.0, std = 0.0
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/neighborData/0/ghostsToReceive
	Arrays of types int64 and int64 have 148 values of which 1 have differing values.
	Statistics of the differences greater than 0:
		max_index = (147,), max = 2, mean = 2.0, std = 0.0
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/nodeList
	Arrays of types int64 and int64 have 610 values of which 5 have differing values.
	Statistics of the differences greater than 0:
		max_index = (303, 1), max = 2, mean = 1.2, std = 0.4
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/ghostRank
	Arrays of types int32 and int32 have 305 values of which 2 have differing values.
	Statistics of the differences greater than 0:
		max_index = (301,), max = 1, mean = 1.0, std = 0.0
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/faceList/__values__
	Arrays of types int8 and int8 have 11256 values of which 11 have differing values.
	Statistics of the differences greater than 0:
		max_index = (11136,), max = 125, mean = 38.18181818181818, std = 38.86531096870595
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/parentIndex
	Arrays of types int64 and int64 have 305 values of which 3 have differing values.
	Statistics of the differences greater than 0:
		max_index = (303,), max = 185, mean = 123.33333333333333, std = 86.50369292052731
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/sets/zpos/__values__
	Arrays of types int64 and int64 have 115 values of which 1 have differing values.
	Statistics of the differences greater than 0:
		max_index = (114,), max = 1, mean = 1.0, std = 0.0
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/sets/zneg/__values__
	Arrays of types int64 and int64 have 115 values of which 1 have differing values.
	Statistics of the differences greater than 0:
		max_index = (114,), max = 1, mean = 1.0, std = 0.0
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/childIndex
	Arrays of types int64 and int64 have 305 values of which 3 have differing values.
	Statistics of the differences greater than 0:
		max_index = (65,), max = 2, mean = 1.3333333333333333, std = 0.4714045207910317
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/localToGlobalMap
	Arrays of types int64 and int64 have 305 values of which 3 have differing values.
	Statistics of the differences greater than 0:
		max_index = (303,), max = 2, mean = 1.3333333333333333, std = 0.4714045207910317
********************************************************************************
********************************************************************************
Error: /Problem/domain/MeshBodies/mesh1/Level0/edgeManager/isExternal
	Arrays of types int32 and int32 have 305 values of which 2 have differing values.
	Statistics of the differences greater than 0:
		max_index = (301,), max = 1, mean = 1.0, std = 0.0
********************************************************************************
********************************************************************************
Error: /Problem/FieldSpecifications/frac/component/__values__
	Scalar values of types int32 and int32 differ: -1, 0.
********************************************************************************
********************************************************************************
Error: /Problem/FieldSpecifications/waterDensity/component/__values__
	Scalar values of types int32 and int32 differ: -1, 0.
********************************************************************************
********************************************************************************
Error: /Problem/FieldSpecifications/separableFace/component/__values__
	Scalar values of types int32 and int32 differ: -1, 0.
********************************************************************************
********************************************************************************
Error: /Problem/FieldSpecifications/sourceTerm/component/__values__
	Scalar values of types int32 and int32 differ: -1, 0.
********************************************************************************
The files are different.
```
</details>

The rank 0  is experiencing the expected differences but rank 3 has mismatches in indexing objects (edges and face lists, ghostToRecieve). 

 Comparing a 6-core run from `develop` or `issue-day/jafranc/defV-fieldSpec` of [https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/physicsSolvers/multiphysics/integratedTests/KGD_ZeroViscosity.xml](url), the numerical values are similar.
 The *fieldSpecification*  xml-block for this test is shared with _KGD_ZeroToughness.xml_  (inserted from _KGDBase.xml_) which is not showing such mismatches.

Do you know what could cause that ?

**Comment by klevzoff** [comment]
> Do you know what could cause that ?

I can't remember if it's this specific test, but I routinely have a couple of tests fail `restartcheck`, but after a few re-runs they eventually pass. I don't know the exact reason, there may be some dependency on the order of neighbor MPI exchanges.

**Comment by rrsettgast** [comment]
There is an order of operations option for the surface generator that fixes this. I'll look up the option when I get back to the computer.

**Comment by rrsettgast** [comment]
@jafranc There is an "mpiCommOrder" that enforces the order that neighbor data is received for surface generation. This should be on for all integrated tests which should take care of the issue you are seeing. Are you running this on quartz?

**Comment by jafranc** [comment]
> @jafranc There is an "mpiCommOrder" that enforces the order that neighbor data is received for surface generation. This should be on for all integrated tests which should take care of the issue you are seeing. Are you running this on quartz?

No, I am running on the Stanford based computer.

**Comment by rrsettgast** [comment]
@jafranc I ran on quartz. Everything is good. All diffs were just the value of `m_component`. Merging

**Pull request merged**
