### PR TITLE
Testing - feature/mazuyer/vtkMeshGenerator branch with updated blt and CMake 3.19.2

### PR DESCRIPTION
**Pull request by bmhan12**
This PR is a test to see if updating blt to develop will resolve Travis CI errors with Pangea/Pecan builds on the `feature/mazuyer/vtkMeshGenerator` branch.

### CODE REVIEW

**Comment by TotoGaz** [comment]
hi @bmhan12 

To sum up things, the cmake upgrade solves the issue for `Pecan-GPU` but we still face some
```
/tmp/build/bin/geosx: error while loading shared libraries: libvtkFiltersStatistics-9.0.so.1: cannot open shared object file: No such file or directory
```
for both `Pecan-CPU` and `Pangea2`?

At least, no more of this `openmpi` issue.

Am I correct that this includes both "double `cmake` upgrade" and `BLT` upgrade?

**Comment by bmhan12** [comment]
@TotoGaz  Yes, this contains both the double CMake and blt upgrades

**Comment by TotoGaz** [comment]
Great, thx.

I've pushed https://github.com/GEOSX/thirdPartyLibs/pull/174 which I think can fix the root cause.
Do you mind if I use your branch `feature/han12/vtkUpdateBlt` for my upcoming commits?

**Comment by bmhan12** [comment]
@TotoGaz  Yes, no problem!

**Comment by TotoGaz** [comment]
Also, why did you select this precise version of BLT? It's a release, something precise?

**Comment by bmhan12** [comment]
@TotoGaz  this was the latest blt develop, but there have been updates since then.

**Comment by TotoGaz** [comment]
Hello @bmhan12, I've managed to solve make https://github.com/GEOSX/GEOSX/pull/1453 work without any `BLT` update and I've upgraded `vtk` https://github.com/GEOSX/GEOSX/pull/1752 & https://github.com/GEOSX/thirdPartyLibs/pull/174.

I think we can not close this PR and deleted `feature/han12/vtkUpdateBlt` 🎉

**Pull request closed without merging**
