### PR TITLE
Docs/andrembcosta/phase field fracture

### PR DESCRIPTION
**Pull request by andrembcosta**
Creating pull request for complete documentation of the Phase-Field Fracture Solver

### CODE REVIEW

**Comment by joshua-white** [comment]
@andrembcosta Can we chat next week before you merge this branch?  I have a branch that completely refactors the constitutive classes, including  your damage models.  It would be easier to add this documentation on that branch, rather than deal with a huge number of merge conflicts.

**Comment by rrsettgast** [comment]
@andrembcosta Can you get this up to date and ready to merge?

**Comment by andrembcosta** [comment]
Sure!

**Comment by andrembcosta** [comment]
I opened #2083 which contains this one, which became too old. We can get rid of this and just merge #2083.

**Pull request closed without merging**
