### PR TITLE
Correct the typo anisotroipic

### PR DESCRIPTION
**Pull request by sytuannguyen**
This PR correct the typo anisotroipic

### CODE REVIEW

**Comment by rrsettgast** [comment]
@sytuannguyen please try to avoid including identical code changes in multiple PR's.

**Review by rrsettgast — COMMENTED** [review]
I think @joshua-white has already addressed this in his PR?

**Comment by joshua-white** [comment]
Not yet, @rrsettgast, but I will.  It is marked with a TODO.

**Comment by rrsettgast** [comment]
@joshua-white I am closing this PR so as not to complicate your life.

**Pull request closed without merging**
