### PR TITLE
Cleanup/refactor poromechanic solvers

### PR DESCRIPTION
**Pull request by sytuannguyen**

### CODE REVIEW

**Comment by TotoGaz** [comment]
@sytuannguyen You seem to have moved a member from `SinglePhasePoromechanicsSolver` to `SinglePhasePoromechanicsSolverEmbeddedFractures`. Can you elaborate a little more on the reasons?

**Comment by CusiniM** [comment]
There is a PR in which the assembly of the PoromechanicsEmbeddedFractures and of many poromechanics solvers is being already refactored. The function `assembleCouplingTerms` is going to be removed since it's not used any more. Check with me, @castelletto1, @joshua-white and/or @rrsettgast if you are interested in the poromechanics solvers because a lot is already going on.

**Comment by sytuannguyen** [comment]
> @sytuannguyen You seem to have moved a member from `SinglePhasePoromechanicsSolver` to `SinglePhasePoromechanicsSolverEmbeddedFractures`. Can you elaborate a little more on the reasons?

This member was implemented in `SinglePhasePoromechanicsSolver` but it is not used by this solver. I guess that it was called by this solver before the implementation of its kernel. However that member is called by and only by the derived solver `SinglePhasePoromechanicsSolverEmbeddedFractures` (This is because kernel is not implemented yet for this one).

**Comment by sytuannguyen** [comment]
> There is a PR in which the assembly of the PoromechanicsEmbeddedFractures and of many poromechanics solvers is being already refactored. The function `assembleCouplingTerms` is going to be removed since it's not used any more. Check with me, @castelletto1, @joshua-white and/or @rrsettgast if you are interested in the poromechanics solvers because a lot is already going on.

@CusiniM Nice, I will close this then. What is the PR that you mentioned?

**Comment by TotoGaz** [comment]
@sytuannguyen can we delete the branch?

**Comment by sytuannguyen** [comment]
@TotoGaz yes I will

**Pull request closed without merging**
