### PR TITLE
Fix Wedge node ordering

### LINKED ISSUE #1442: [Bug] Internal Mesh C3D6 elements generated and/or output incorrectly
**Describe the bug**
I'm trying to create a simple DFN using an internally generated mesh with C3D6 elements.  While debugging the results, I've found that:

1) The silo/vtk files output tend to look tangled
2) I'm not able to split the mesh along the diagonal face as expected (I was able to get this to work for C3D4 elements, but maybe this was a mistake on my part)

image

**To Reproduce**

Here is a simple xml file that re-creates the issue:

```xml
<?xml version="1.0" ?>

<Problem>
  <Solvers
    gravityVector="{ 0.0, 0.0, -0.0 }">
    <Hydrofracture
      name="hydrofracture"
      solidSolverName="lagsolve"
      fluidSolverName="SinglePhaseFlow"
      couplingTypeOption="FIM"
      logLevel="1"
      discretization="FE1"
      targetRegions="{ Domain, Fracture }"
      contactRelationName="fractureContact"
      maxNumResolves="2"
      initialDt="0.1">

      <NonlinearSolverParameters
        newtonTol="1.0e-6"
        lineSearchAction="Attempt"
        maxTimeStepCuts="10"
        newtonMaxIter="40"/>
      <LinearSolverParameters
        solverType="fgmres"
        preconditionerType="mgr"
        krylovTol="1e-6"
        krylovAdaptiveTol="1"
        krylovWeakestTol="1e-4"/>
    </Hydrofracture>

    <SolidMechanicsLagrangianSSLE
      name="lagsolve"
      timeIntegrationOption="QuasiStatic"
      logLevel="0"
      discretization="FE1"
      targetRegions="{ Domain, Fracture }"
      solidMaterialNames="{ rock }"
      contactRelationName="fractureContact"/>

    <SinglePhaseFVM
      name="SinglePhaseFlow"
      logLevel="1"
      discretization="singlePhaseTPFA"
      fluidNames="{ water }"
      solidNames="{ rock }"
      targetRegions="{ Fracture }"
      meanPermCoeff="0.8"/>

    <SurfaceGenerator
      name="SurfaceGen"
      logLevel="0"
      fractureRegion="Fracture"
      targetRegions="{ Domain }"
      nodeBasedSIF="1"
      solidMaterialNames="{ rock }"
      rockToughness="1.0e6"/>
  </Solvers>

  <Events
    maxCycle="2"
    logLevel="1">

    <PeriodicEvent
      name="silo"
      timeFrequency="1"
      target="/Outputs/siloOutput"/>

    <SoloEvent
      name="preFracture"
      target="/Solvers/SurfaceGen"/>
  </Events>

  <ElementRegions>
    <CellElementRegion
      name="Domain"
      cellBlocks="{ cb1 }"
      materialList="{ water, rock }"/>

    <SurfaceElementRegion
      name="Fracture"
      defaultAperture="1.0e-4"
      materialList="{ water, rock }"/>
  </ElementRegions>

  <NumericalMethods>
    <FiniteElements>
      <FiniteElementSpace
        name="FE1"
        order="1"/>
    </FiniteElements>

    <FiniteVolume>
      <TwoPointFluxApproximation
        name="singlePhaseTPFA"
        fieldName="pressure"
        coefficientName="permeability"/>
    </FiniteVolume>
  </NumericalMethods>

  <Constitutive>
    <CompressibleSinglePhaseFluid
      name="water"
      defaultDensity="1000"
      defaultViscosity="0.005"
      referencePressure="0.0"
      referenceDensity="1000"
      compressibility="5e-10"
      referenceViscosity="5.0e-3"
      viscosibility="0.0"/>

    <PoroElasticIsotropic
      name="rock"
      defaultDensity="2650"
      defaultBulkModulus="20.0e9"
      defaultShearModulus="12.0e9"
      BiotCoefficient="1"
      compressibility="1e-12"
      referencePressure="1e6"/>
  </Constitutive>

  <Outputs>
    <Silo
      name="siloOutput"
      plotLevel="3"
      parallelThreads="16"/>
  </Outputs>

  <Mesh>
    <InternalMesh
      name="internal_mesh"
      elementTypes="{ C3D6 }"
      xCoords="{ 0, 1 }"
      yCoords="{ 0, 1 }"
      zCoords="{ 0, 1 }"
      nx="{ 1 }"
      ny="{ 1 }"
      nz="{ 1 }"
      cellBlockNames="{ cb1 }"/>
  </Mesh>

  <FieldSpecifications>
    <FieldSpecification
      name="frac"
      initialCondition="1"
      setNames="{ fracture }"
      objectPath="faceManager"
      fieldName="ruptureState"
      scale="1"/>
  </FieldSpecifications>

  <Geometry>
    <BoundedPlane
        name="fracture"
        normal="{ -1.0000, 1.0000, 0.0000 }"
        origin="{ 0, 0, 0 }"
        lengthVector="{ 1.0000, 1.0000, 0.0000 }"
        widthVector="{ 0.0000, 0.0000, 1.0000 }"
        dimensions="{ 20, 20 }"
        tolerance="1e-4"/>
    <!-- <BoundedPlane
        name="fracture"
        normal="{ 1.0000, 1.0000, 0.0000 }"
        origin="{ 0, 0, 0 }"
        lengthVector="{ 1.0000, -1.0000, 0.0000 }"
        widthVector="{ 0.0000, 0.0000, 1.0000 }"
        dimensions="{ 20, 20 }"
        tolerance="1e-4"/> -->
  </Geometry>
</Problem>

```

### PR DESCRIPTION
**Pull request by AntoineMazuyer**
Francois: I modified very lines of actual code, but I updated a mesh file that was producing negative volumes in Visit.

Fixes #1442

### CODE REVIEW

**Comment by cssherman** [comment]
@AntoineMazuyer - The node ordering seems to be mangled in the internal mesh generator as well #1442 .  Are these broken in the same way, or do will that require additional work?

**Review by rrsettgast — APPROVED** [review]

**Comment by AntoineMazuyer** [comment]
@cssherman I thought that the node ordering of the internal mesh generator was correct if I record well the conversation I had with @jhuang2601

**Comment by francoishamon** [comment]
I looked into the ordering problems for the wedge (import from the GMSH format, export to VTK/Silo).

**Input**
My understanding is that GMSH stores the wedge nodes in this ordering:

while GEOSX expects this node ordering:
image
so the map GMSH -> GEOSX is:
```
GEOSX node id: 0 1 2 3 4 5
GMSH  node id: 0 3 1 4 2 5
```
I just pushed a small fix because in this branch we were not using node 4 of GMSH (and we were using twice node 3 instead). @AntoineMazuyer Could you please confirm that this is correct and that I did not do any mistake?

**Output**
Since VTK and Silo do not use the same ordering for wedges, we need two different maps when we export the wedges for visualization: one for VTK, and one for Silo.

My understanding is that VTK stores the wedge nodes in this ordering:

while Silo expects this node ordering:
image
so the map GEOSX -> VTK is:
```
VTK node id:   0 1 2 3 4 5
GEOSX node id: 0 4 2 1 5 3
```
and the map GEOSX -> Silo is:
```
Silo node id:  0 1 2 3 4 5
GEOSX node id: 0 1 3 2 4 5
```
To check the input and output maps, I used the following integrated tests:
https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/physicsSolvers/simplePDE/integratedTests/10x5x15Wedges_LaplaceVEM.xml
https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_wedge_gravity.xml
plus the test posted by @cssherman.

I confirm that now on these tests we can visualize properly the wedge meshes coming from the InternalMeshGenerator and PAMELA.

**Comment by francoishamon** [comment]
> @AntoineMazuyer - The node ordering seems to be mangled in the internal mesh generator as well #1442 . Are these broken in the same way, or do will that require additional work?

@cssherman I checked with your xml file, and this PR should fix your visualization problem for both Visit and Paraview.

**Comment by francoishamon** [comment]
The last point that I want to mention is the computation of the wedge volumes in Visit, which was the original reason for the PR. Visit seems to be sensitive to the orientation of the faces in the wedge when it computes the volumes, which explains why a mesh that has a positive volume in GEOSX can be displayed with a negative volume in Visit.

To be specific, the two meshes below:
[cube_10x10x10_wedge_new.txt](https://github.com/GEOSX/GEOSX/files/6703934/cube_10x10x10_wedge_new.txt)
[cube_10x10x10_wedge.txt](https://github.com/GEOSX/GEOSX/files/6703935/cube_10x10x10_wedge.txt)
produce the same positive volumes in GEOSX, but only one is displayed with negative volumes in Visit so we will have to be careful with that next time we use an external wedge mesh and display it in Visit. For this reason, I flipped the ordering of the node in [this mesh](https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/cube_10x10x10_wedge.msh) to make sure that it is displayed with positive volumes in Visit.

For internal wedge meshes, the current PR yields positive volumes in GEOSX, in Paraview, and in Visit.

**Comment by francoishamon** [comment]
@AntoineMazuyer I cannot ask you for a review because you opened this PR, but if you agree with the changes, it is ready to be merged

**Review by cssherman — APPROVED** [review]

**Comment by francoishamon** [comment]
This PR does not break the integrated tests, so I am going to merge it when the Travis tests are complete.

**Pull request merged**
