### PR TITLE
Remove registration of velocity and acceleration in QS simulations.

### PR DESCRIPTION
**Pull request by CusiniM**
In quasi-static simulations we do not need velocity and acceleration. This PR removes the registration of these two variables from the SolidMechanicsSolver for QS models. 

@jhuang2601, this should fix your issue with  https://github.com/GEOSX/GEOSX/pull/1730

Rebaseline: https://github.com/GEOSX/integratedTests/pull/269

### CODE REVIEW

**Review by jhuang2601 — APPROVED** [review]
Nice job!

**Comment by jhuang2601** [comment]
With this change, probably all the integratedTests should be reran.

**Review by rrsettgast — APPROVED** [review]

**Comment by TotoGaz** [comment]
This PR clearly conflicts with https://github.com/GEOSX/GEOSX/pull/2098/files 
Maybe you should wait for it o be merged first?
Then only after move the `registerExtrinsicData` calls?

**Comment by CusiniM** [comment]
> This PR clearly conflicts with https://github.com/GEOSX/GEOSX/pull/2098/files Maybe you should wait for it o be merged first? Then only after move the `registerExtrinsicData` calls?

I don't think the conflicts will be that hard to handle and @jhuang2601 has been waiting for this for months so I was planning to get it merged today.

**Comment by TotoGaz** [comment]
@jhuang2601 up to you 😉

**Comment by francoishamon** [comment]
Don't worry about the conflicts with the PR on extrinsic data, you can go ahead and merge, I will just resolve the conflicts in the extrinsic data PR after, it will be easy and quick.

**Comment by rrsettgast** [comment]
This shouldn't be in the merge queue if it is a draft!!! Changing to a full PR.

**Comment by CusiniM** [comment]
> This shouldn't be in the merge queue if it is a draft!!! Changing to a full PR.

I was merging develop and creating the new baselines but it's actually ready. I had left it as draft only start the CI once with the correct integratedTests tag. Anywayas, I ll move it back once done.

**Pull request merged**
