### PR TITLE
add reinit method to waveSolverBase

### PR DESCRIPTION
**Pull request by labesse40**
This PR is about overwriting the reinit() method in WaveSolverBase to be able to reinitialize variables in the solver when using pygeosx.

### CODE REVIEW

**Comment by rrsettgast** [comment]
@labesse40 Did this fix your problem?

**Comment by labesse40** [comment]
This is just an omission of the reinit() method to be overwriten in WaveSolverBase, it should have been part of the previous pygeosx PR but has no impact on the issue we mentioned earlier.

**Comment by labesse40** [comment]
> @labesse40 Did this fix the problem that @henricalandra64 was seeing?
This is just an omission of the reinit() method to be overwriten in WaveSolverBase, it should have been part of the previous pygeosx PR but has no impact on the issue we mentioned earlier.

**Comment by labesse40** [comment]
> @labesse40 Did this fix the problem that @henricalandra64 was seeing?

This is just an omission of the reinit() method to be overwriten in WaveSolverBase, it should have been part of the previous pygeosx PR but has no impact on the issue we mentioned earlier.

**Review by francoishamon — APPROVED** [review]

**Review by sframba — APPROVED** [review]

**Comment by francoishamon** [comment]
I checked that this PR does not break the integrated tests, so I am going to merge it since it is at the top of the merge queue

**Pull request merged**
