### PR TITLE
Upgrade to doxygen 1.8.20

### PR DESCRIPTION
**Pull request by bmhan12**
This PR modifies Travis CI and quartz host-configs to use doxygen 1.8.20.

https://github.com/GEOSX/thirdPartyLibs/pull/110
https://github.com/GEOSX/LvArray/pull/202

### CODE REVIEW

**Comment by bmhan12** [comment]
The following components have warnings (~200) from doxygen:

- LvArray
- common
- dataRepository
- finiteElement
- finiteVolume
- linearAlgebra
- managers
- physicsSolvers

The warnings are identical between Travis CI and quartz.

**Comment by af1990** [comment]
Maybe I missed it ... but is there a specific reason why we don't use the latest version (1.8.20)?

**Comment by bmhan12** [comment]
> Maybe I missed it ... but is there a specific reason why we don't use the latest version (1.8.20)?

I did try 1.8.20 and 1.8.19, but could not build them from source on quartz. 1.8.20 was the latest version that worked for me.

**Comment by klevzoff** [comment]
I've fixed all warnings in `linearAlgebra` and some more. With doxygen 1.8.18 all warnings left are bogus ones related to undocumented return type of `void` functions - these seem to be caused in some way by `GEOSX_HOST_DEVICE`, since removing that decoration gets rid of the warnings (at least some of them). With 1.8.20 I do **not** get these warnings, but I'm getting two **new** strange warnings in `BufferOps_inline.hpp` which I did not have with 1.8.18. Still, I think trying to upgrade to 1.8.20 is worthwhile, but it depends on how big the build problems on quartz are (I encountered none on Ubuntu).

**Comment by rrsettgast** [comment]
I was able to build 1.8.20 on LC.

**Comment by rrsettgast** [comment]
@klevzoff I can't get the same errors on Quartz. Can you see the same errors on your machine?

**Comment by klevzoff** [comment]
> @klevzoff I can't get the same warnings/errors on Quartz. Can you see the same errors on your machine?

Yes, exactly the same ones

**Comment by rrsettgast** [comment]
@klevzoff I just tried to remove all doxygen from the `dataRepository/BufferOps.hpp` file (which includes the `BufferOps_inline.hpp), since it doesn't even have a doxygen tag on the file itself. I don't know why this is being processed at all. Perhaps you can manually exclude the file. Since they are not doxygenated, it wouldn't be the worst temporary solution.

**Review by klevzoff — APPROVED** [review]
This passes the documentation check now

**Pull request merged**
