### PR TITLE
Reorganize verification examples

### PR DESCRIPTION
**Pull request by jhuang2601**
Based on our doc day discussion, we need to reorganize verification examples by adding another directory level.
Here is the proposed restructuring of the Examples section, which is application-oriented:

Validation Studies
   - Single Phase Flow
        - ...

   - Carbon Storage
        - CO2 Plume Evolution and Leakage Through an Abandoned Well

   - Fault Mechanics
        - Single Fracture Under Shear Compression
        - Fracture Intersection Problem
        - Sneddon’s Problem
        - Mandel’s Problem
        - Verification of induced stresses along a fault in a pressurized reservoir
      
   - Hydraulic Fracture
        - Toughness dominated KGD hydraulic fracture
        - Viscosity dominated KGD hydraulic fracture
        - Validating KGD Hydraulic Fracture with Experiment
        - Toughness-Storage-Dominated Penny Shaped Hydraulic Fracture
        - Viscosity-Storage-Dominated Penny Shaped Hydraulic Fracture
        - Viscosity-Storage-Dominated PKN Hydraulic Fracture
        - Proppant Slot Test

   - Wellbore Problems
        - Kirsch Wellbore Problem
        - Cased Elastic Wellbore Problem
        - Deviated Elastic Wellbore Problem
        - Elasto-Plastic Near-Well Deformation
        - Modified Cam-Clay Model for Wellbore Problems
        - Deviated Poro-Elastic Wellbore Subjected to Fluid Injection
        - Deviated Poro-Elastic Wellbore Subjected to In-situ Stresses and Pore Pressure
        - Vertical PoroElasto-Plastic Wellbore Problem

### CODE REVIEW

**Review by herve-gross — APPROVED** [review]
I like the new structure. The file paths become quite deep though (lots of ../..) and it is hard for me to make sure that we do not have a missing change in the paths. What is there seems OK, but we will need to compile Sphinx and verify the files afterward to be sure. Thank you for this detailed work.

**Comment by joshua-white** [comment]
This looks good to me.  My only suggestion is to change `CO2 Flow` to `Carbon Storage`.  Also, do we have this building on a dummy branch on readthedocs?  Would be good to live preview it for any issues being created.

**Review by joshua-white — APPROVED** [review]

**Comment by jhuang2601** [comment]
> This looks good to me. My only suggestion is to change `CO2 Flow` to `Carbon Storage`. Also, do we have this building on a dummy branch on readthedocs? Would be good to live preview it for any issues being created.

Sure, will change it. We do have a dummy branch and check on readthedocs, which helped me to find some issues.

**Comment by bmhan12** [comment]
@jhuang2601 

This Azure Pipelines job looks to be failing because we are
surpassing Microsoft's[ 10GB disk space limit](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts#capabilities-and-limitations) for their hosted agents ([Travis's limit is 50 GB](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system)):
https://dev.azure.com/GEOSX/GEOSX/_build/results?buildId=81&view=logs&j=62241cba-44b9-5a3d-3058-39fe51bd58d2

I'm looking into it now, but if this is holding up your PR, let me know and I can move this job back onto Travis CI.

**Pull request merged**
