### PR TITLE
test osx build

### LINKED ISSUE #1149: Mac build pattern won't work anymore with brew
As pointed by @af1990 in build https://travis-ci.com/github/GEOSX/GEOSX/jobs/382490297
There is something wrong with brew installing `open-mpi`.

PR https://github.com/Homebrew/brew/pull/8513 has disabled the functionality we were relying on (~installing old versions from an URL).
It's been deprecated since https://github.com/MikeMcQuaid/brew/commit/a35825ff230154fbab37c2ea936af4ebee65f186 (3 months), did not see it coming though.

There seems to be a new `brew extract` way imposed.
I quite don't get what they mean ; I'll give it a shot.
But I am not willing to spend to much time.

So If we cannot make it, I suggest that for the moment we give up this way of maintaining a specific version of `open-mpi`: let's rely on what `homebrew` wants. The result is that like the old days, from time to time we have to recompile the TPLs with the latest open-mpi.

Any comments?

### PR DESCRIPTION
**Pull request by TotoGaz**
Fixes #1149

### CODE REVIEW

**Comment by af1990** [comment]
Removing _Draft_ to allow travis to run.

**Comment by TotoGaz** [comment]
@af1990 I cannot approve since I am the author of the PR. But you seem to be able to do it, so you should go for it.

**Review by af1990 — APPROVED** [review]

**Comment by TotoGaz** [comment]
> @af1990 af1990 self-requested a review 1 minute ago

@af1990 call the police 🚓

**Comment by TotoGaz** [comment]
@rrsettgast we are ready to merge the fix. Can we go now? What about the revert on `develop`?
I think we could simply PR a simple revert?

**Review by rrsettgast — APPROVED** [review]

**Pull request merged**
