### PR TITLE
XML Redundancy Tool

### PR DESCRIPTION
**Pull request by cssherman**

### CODE REVIEW

**Comment by cssherman** [comment]
The updated xml files in this PR need to be checked to see if we want to add any additional attributes to the redundancy whitelist:

- component (this shows up a lot where we apply a BC to the 0th component of a vector)

**Comment by rrsettgast** [comment]
Nice!

**Comment by sytuannguyen** [comment]
This xml tool is so nice! Is it possible to generate xml from simple geometrical/physical description of a given problem?

**Review by joshua-white — APPROVED** [review]
This is awesome.

**Pull request merged**
