### PR TITLE
VTK writes ghost cells conditionally

### LINKED ISSUE #2257: Wave propagation tests need new baselines after lifo PR merge.
Wave propagation tests should have been rebaselined after merging https://github.com/GEOSX/GEOSX/commit/29be27d758e6f7b3db955d96002e460d63a9a5b8 

They are now failing.

### PR DESCRIPTION
**Pull request by TotoGaz**
Adds the `writeGhostCells` keyword to the `VTK` output. Defaults to `false`.
- Successfully tested on fractures.
- Successfully tested on serial runs.

@jeannepellerin Can you validate the fix?

Resolves https://github.com/GEOSX/GEOSX/issues/2144
Resolves #2257 

Rebaseline done in https://github.com/GEOSX/integratedTests/pull/292

### CODE REVIEW

**Comment by rrsettgast** [comment]
@jeannepellerin can you confirm that this PR addresses the issue #2144 that you were having?

**Comment by AntoineMazuyer** [comment]
For me I think the solution you proposed is good. Default behavior --> no ghost cells writing.

**Review by AntoineMazuyer — APPROVED** [review]

**Comment by margauxraguenel** [comment]
@jeannepellerin I checked the output on a simple simulation and it fixes the problem I raised before.

Thanks @TotoGaz

**Review by jeannepellerin — APPROVED** [review]
Looks good !

**Comment by TotoGaz** [comment]
Thx @margauxraguenel , I'll proceed to the last checks (integrated tests, etc.) and eventually merge.

**Pull request merged**
