### PR TITLE
Bugfix for #1550

### PR DESCRIPTION
**Pull request by klevzoff**
Resolves https://github.com/GEOSX/GEOSX/issues/1550 (hopefully, as I don't have gcc-8.1.0 and can't check)

### CODE REVIEW

**Comment by CusiniM** [comment]
It still gives the same error. I guess a possible fix would be to use a `stackArray` instead but it requires some changes.

- Do we really need to support gcc 8.1.0? If supporting it is a must then we should probably add it to the CI.

**Review by rrsettgast — APPROVED** [review]

**Comment by corbett5** [comment]
GCC 8.1.0 is the latest GCC available on Quartz so I think we should definitively try and support it.

**Comment by CusiniM** [comment]
> GCC 8.1.0 is the latest GCC available on Quartz so I think we should definitively try and support it.

Then, I am not sure what we can do to fix this. I thought quartz had some newer versions of gcc...

**Comment by klevzoff** [comment]
@CusiniM can you try building this branch on Quartz once again? I rebased it though, so don't pull but do something like:
```
git fetch origin
git reset --hard origin/bugfix/klevzoff/issue-1550
```

**Comment by rrsettgast** [comment]
@klevzoff This compiles using gcc8.1 on quartz.

**Comment by klevzoff** [comment]
@rrsettgast we'll consider it a win then :)

**Comment by corbett5** [comment]
What a silly fix. How did you figure it out?

**Comment by klevzoff** [comment]
> What a silly fix. How did you figure it out?

Yep. Since the compiler was clearly choosing to treat the local variable as non-constexpr (hence the VLA warning), I had to make sure it doesn't have a choice by removing the local variable.

**Pull request merged**
