### PR TITLE
Thermo-Hydro-Mechanical coupling

### PR DESCRIPTION
**Pull request by sytuannguyen**
This PR adds options for the computation of thermal stress. Only weak thermal coupling is considered (convection is not considered and temperature change due to mechanical deformation is ignored), i.e. temperature is simulated separately then used to update stress and porosity. Applications for wellbore subjected to thermal loading will be considered for benchmarking purpose.

### CODE REVIEW

**Comment by sytuannguyen** [comment]
An example of stress generated in a constrained cube by applying a temperature raise of 100 °C, the thermal stress coefficient (the product of the bulk modulus and the linear thermal expansion coefficient-TEC) is of 1e4 (Pa/°C)

image

**Comment by sytuannguyen** [comment]
Example of stress generated in a constrained cube heated on one left face at steady state regime. Temperature is first computed by the LaplaceFEM solver, it is then used to compute the thermal stress in the thermoelastic solver.

image

**Comment by sytuannguyen** [comment]
Example of stress generated around a wellbore by temperature change in the well (steady state regime for instant)

image

**Comment by sytuannguyen** [comment]
Benchmark a thermoelastic wellbore at steady state regime. Temperature and stress around the borehole are generated by apply a temperature raise of 100°C in the well.

image

image

**Comment by rrsettgast** [comment]
@sytuannguyen I don't think this is how we want to do thermal stresses. We would want to embed this into the constitutive response.

**Comment by sytuannguyen** [comment]
> We would want to embed this into the constitutive response.

@rrsettgast you can find the thermoelastic constitutive update class that is just a clone of the poroelastic constituive update. Here I consider weak thermal coupling but I plan to work on strong thermal coupling also (in another PR). Please provide some detail of your plan so I can follow. Thanks!

**Comment by sytuannguyen** [comment]
Thermal stress in transient regime

At 1s of thermal diffusion:
image

At 10s of thermal diffusion:
image

**Comment by sytuannguyen** [comment]
Benchmark temperature and thermal stress distribution around a wellbore in transient regime

image

**Comment by sytuannguyen** [comment]
THM problems with weak thermal coupling:
-[] Temperature distribution is computed from pure thermal diffusion solver
-[] Computed temperature is used to update stress and porosity/density in the kernel
-[] Validation against relevant results given by Wang and Papamichos (1994)

**Comment by sytuannguyen** [comment]
Thermal induced pore pressure around a wellbore

image

**Comment by sytuannguyen** [comment]
Good agreement between numerical results and analytical results for a THM coupled problem with weak thermal coupling.
image

**Comment by sytuannguyen** [comment]
Benchmark a short term diffusion THM problem
1305f40bcac90f7bda39df3394060d5b6de58fa9

**Pull request closed without merging**
