### PR TITLE
Update the style of single phase face BC

### PR DESCRIPTION
**Pull request by sytuannguyen**
This PR addresses the first part of the issue https://github.com/GEOSX/GEOSX/issues/2163

Following the suggestion of @francoishamon, classes `DirichletFaceBasedAssemblyKernel` and `DirichletFaceBasedAssemblyKernelFactory` are added for replancing the outdated struct `FaceDirichletBCKernel`.

### CODE REVIEW

**Review by francoishamon — APPROVED** [review]
Looks good, thanks @sytuannguyen. Don't forget to uncrustify when you are done.

Did you check the integrated tests to make sure everything still works after your changes?

**Comment by jhuang2601** [comment]
@francoishamon @sytuannguyen @CusiniM @TotoGaz @herve-gross 
As requested, I've reran all the integratedTests with this PR on Pecan. Unfortunately, several unexpected fail runs are detected:
```
      Status     :  TestCase                                        :  Elapsed :  Resources :  TestStep     :  OutFile                                                                                                                     
     ---------- :  ----------------------------------------------- :  ------- :  --------- :  ------------ :  ----------------------------------------------------------------------------------------------------------------------------
     FAIL RUN   :  co2_thermal_obl_3d_01                           :  0:00:03 :  0:00:03   :  geosx        :  thermalMultiphaseFlow/co2_thermal_obl_3d_01/co2_thermal_obl_3d_01.data                                                      
                :                                                  :          :            :               :  thermalMultiphaseFlow/co2_thermal_obl_3d_01/co2_thermal_obl_3d_01.err                                                       
     FAIL RUN   :  WillisRichardsPermeability_EDFM_01              :  0:00:02 :  0:00:02   :  geosx        :  poromechanicsFractures/WillisRichardsPermeability_EDFM_01/WillisRichardsPermeability_EDFM_01.data                           
                :                                                  :          :            :               :  poromechanicsFractures/WillisRichardsPermeability_EDFM_01/WillisRichardsPermeability_EDFM_01.err                            
     FAIL RUN   :  PoroElastic_staircase_co2_3d_1-1-1              :  0:00:11 :  0:00:11   :  geosx        :  poroElasticCoupling/PoroElastic_staircase_co2_3d_1-1-1/PoroElastic_staircase_co2_3d_1-1-1.data                              
                :                                                  :          :            :               :  poroElasticCoupling/PoroElastic_staircase_co2_3d_1-1-1/PoroElastic_staircase_co2_3d_1-1-1.err                               
     FAIL RUN   :  PoroElastic_deadoil_3ph_baker_2d1-1-1           :  0:00:02 :  0:00:02   :  geosx        :  poroElasticCoupling/PoroElastic_deadoil_3ph_baker_2d1-1-1/PoroElastic_deadoil_3ph_baker_2d1-1-1.data                        
                :                                                  :          :            :               :  poroElasticCoupling/PoroElastic_deadoil_3ph_baker_2d1-1-1/PoroElastic_deadoil_3ph_baker_2d1-1-1.err                         
     FAIL RUN   :  Sneddon_smoke_01                                :  0:00:01 :  0:00:01   :  geosx        :  embeddedFractures/Sneddon_smoke_01/Sneddon_smoke_01.data embeddedFractures/Sneddon_smoke_01/Sneddon_smoke_01.err            
     FAIL RUN   :  EmbFrac_Compression_Frictionless_01             :  0:00:01 :  0:00:01   :  geosx        :  embeddedFractures/EmbFrac_Compression_Frictionless_01/EmbFrac_Compression_Frictionless_01.data                              
                :                                                  :          :            :               :  embeddedFractures/EmbFrac_Compression_Frictionless_01/EmbFrac_Compression_Frictionless_01.err                               
     FAIL RUN   :  EmbFrac_Compression_CoulombFriction_01          :  0:00:01 :  0:00:01   :  geosx        :  embeddedFractures/EmbFrac_Compression_CoulombFriction_01/EmbFrac_Compression_CoulombFriction_01.data                        
                :                                                  :          :            :               :  embeddedFractures/EmbFrac_Compression_CoulombFriction_01/EmbFrac_Compression_CoulombFriction_01.err                         
     FAIL RUN   :  ContactMechanics_UnstructuredCrack_01           :  0:00:02 :  0:00:02   :  geosx        :  contactMechanics/ContactMechanics_UnstructuredCrack_01/ContactMechanics_UnstructuredCrack_01.data                           
                :                                                  :          :            :               :  contactMechanics/ContactMechanics_UnstructuredCrack_01/ContactMechanics_UnstructuredCrack_01.err                            
     FAIL RUN   :  ContactMechanics_TFrac_01                       :  0:00:02 :  0:00:02   :  geosx        :  contactMechanics/ContactMechanics_TFrac_01/ContactMechanics_TFrac_01.data                                                   
                :                                                  :          :            :               :  contactMechanics/ContactMechanics_TFrac_01/ContactMechanics_TFrac_01.err                                                    
     FAIL RUN   :  ContactMechanics_SingleFracCompression_01       :  0:00:08 :  0:00:08   :  geosx        :  contactMechanics/ContactMechanics_SingleFracCompression_01/ContactMechanics_SingleFracCompression_01.data                   
                :                                                  :          :            :               :  contactMechanics/ContactMechanics_SingleFracCompression_01/ContactMechanics_SingleFracCompression_01.err                    
     FAIL RUN   :  dead_oil_wells_hybrid_2d_01                     :  0:00:07 :  0:00:07   :  geosx        :  compositionalMultiphaseWell/dead_oil_wells_hybrid_2d_01/dead_oil_wells_hybrid_2d_01.data                                    
                :                                                  :          :            :               :  compositionalMultiphaseWell/dead_oil_wells_hybrid_2d_01/dead_oil_wells_hybrid_2d_01.err                                     
     FAIL RUN   :  isothermalLeakyWell_smoke_3d_01                 :  0:00:30 :  0:00:30   :  geosx        :  compositionalMultiphaseFlow/isothermalLeakyWell_smoke_3d_01/isothermalLeakyWell_smoke_3d_01.data                            
                :                                                  :          :            :               :  compositionalMultiphaseFlow/isothermalLeakyWell_smoke_3d_01/isothermalLeakyWell_smoke_3d_01.err                             
     FAIL RUN   :  thermalLeakyWell_smoke_3d_01                    :  0:04:21 :  0:04:21   :  geosx        :  compositionalMultiphaseFlow/thermalLeakyWell_smoke_3d_01/thermalLeakyWell_smoke_3d_01.data                                  
                :                                                  :          :            :               :  compositionalMultiphaseFlow/thermalLeakyWell_smoke_3d_01/thermalLeakyWell_smoke_3d_01.err                                   
     FAIL RUN   :  deadoil_2ph_staircase_gravity_segregation_3d_01 :  0:00:21 :  0:00:21   :  geosx        :  compositionalMultiphaseFlow/deadoil_2ph_staircase_gravity_segregation_3d_01/deadoil_2ph_staircase_gravity_segregation_3d_01.data
                :                                                  :          :            :               :  compositionalMultiphaseFlow/deadoil_2ph_staircase_gravity_segregation_3d_01/deadoil_2ph_staircase_gravity_segregation_3d_01.err
     FAIL RUN   :  DryFrac_StaticPenny_PrismElem_01                :  0:00:11 :  0:00:11   :  geosx        :  SurfaceGenerator/DryFrac_StaticPenny_PrismElem_01/DryFrac_StaticPenny_PrismElem_01.data                                     
                :                                                  :          :            :               :  SurfaceGenerator/DryFrac_StaticPenny_PrismElem_01/DryFrac_StaticPenny_PrismElem_01.err                                      
     FAIL RUN   :  kgdValidation_smoke_01                          :  0:00:02 :  0:00:02   :  geosx        :  HydrofracturingSolver/kgdValidation_smoke_01/kgdValidation_smoke_01.data                                                    
                :                                                  :          :            :               :  HydrofracturingSolver/kgdValidation_smoke_01/kgdValidation_smoke_01.err                                                     
     FAIL RUN   :  heterogeneousInSitu_smoke_01                    :  0:00:11 :  0:00:11   :  geosx        :  HydrofracturingSolver/heterogeneousInSitu_smoke_01/heterogeneousInSitu_smoke_01.data                                        
                :                                                  :          :            :               :  HydrofracturingSolver/heterogeneousInSitu_smoke_01/heterogeneousInSitu_smoke_01.err                                         
     FAIL RUN   :  pennyShapedToughnessDominated_smoke_01          :  0:00:05 :  0:00:05   :  geosx        :  HydrofracturingSolver/pennyShapedToughnessDominated_smoke_01/pennyShapedToughnessDominated_smoke_01.data                    
                :                                                  :          :            :               :  HydrofracturingSolver/pennyShapedToughnessDominated_smoke_01/pennyShapedToughnessDominated_smoke_01.err                     
     FAIL RUN   :  pennyShapedViscosityDominated_smoke_01          :  0:00:06 :  0:00:06   :  geosx        :  HydrofracturingSolver/pennyShapedViscosityDominated_smoke_01/pennyShapedViscosityDominated_smoke_01.data                    
                :                                                  :          :            :               :  HydrofracturingSolver/pennyShapedViscosityDominated_smoke_01/pennyShapedViscosityDominated_smoke_01.err                     
     FAIL RUN   :  pknViscosityDominated_smoke_01                  :  0:00:06 :  0:00:06   :  geosx        :  HydrofracturingSolver/pknViscosityDominated_smoke_01/pknViscosityDominated_smoke_01.data                                    
                :                                                  :          :            :               :  HydrofracturingSolver/pknViscosityDominated_smoke_01/pknViscosityDominated_smoke_01.err                                     
     FAIL RUN   :  walshQuarter01                                  :  0:00:05 :  0:00:05   :  geosx        :  HydrofracturingSolver/walshQuarter01/walshQuarter01.data HydrofracturingSolver/walshQuarter01/walshQuarter01.err            
     ---------- :  ----------------------------------------------- :  ------- :  --------- :  ------------ :  ----------------------------------------------------------------------------------------------------------------------------
     FAIL CHECK :  hybridHexPrism_LaplaceVEM_smoke_01              :  0:00:03 :  0:00:03   :  restartcheck :  simplePDE/hybridHexPrism_LaplaceVEM_smoke_01/hybridHexPrism_LaplaceVEM_smoke_01.data                                        
                :                                                  :          :            :               :  simplePDE/hybridHexPrism_LaplaceVEM_smoke_01/hybridHexPrism_LaplaceVEM_smoke_01.err                                         
     ---------- :  ----------------------------------------------- :  ------- :  --------- :  ------------ :  ----------------------------------------------------------------------------------------------------------------------------
```
By checking the .data files, various errors are reported:

for ContactMechanics_UnstructuredCrack (nan values for residual):

```
Time: 0s, dt:1s, Cycle: 0
  Number of element for each fracture state: stick:          120 | slip:             0 | open:             0
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
    ( Rdisplacement, Rtraction, Rtotal ) = (    1.000000e+00,    1.000000e+00,    1.000000e+00 );
    ( R ) = ( 1.00e+00 ) ; 
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  1
    ( Rdisplacement, Rtraction, Rtotal ) = ( nan            , -nan           , nan             );
    ( R ) = ( nan  ) ; 
    Last LinSolve(iter,res) = (   1, -nan ) ; 
```

For co2_thermal_obl_3d (unconvergence):
```
New dt = 50000
    Attempt:  1, ConfigurationIter:  0, NewtonIter:  0
    ( Rflow ) = ( 1.23e+01 ) ;
    ( R ) = ( 1.23e+01 ) ; 
    Solution check failed. Newton loop terminated.
New dt = 25000
Convergence not achieved.
***** ERROR
***** LOCATION: /lustre4/scratch/j0551570/geosx/SyTuan/GEOSX/src/coreComponents/physicsSolvers/SolverBase.cpp:743
***** Controlling expression (should be false): true
***** Rank 0: Nonconverged solutions not allowed. Terminating...
```

For walshQuarter (just crashed at first step):
```
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh1, Level0, void, void
mesh1/Level0/void/void/water allocated 8 quadrature points
mesh1/Level0/void/void/rock allocated 8 quadrature points
Time: 0s, dt:0.0001s, Cycle: 0
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
singlePhaseTPFA
    ( R ) = ( 8.30e-01 ) ; 
		Linear Solver | Success | Iterations: 1 | Final Rel Res: -nan | Setup Time: 2.75492 s | Solve Time: 0.0144221 s
```

I guess these issues/errors are not introduced by this PR.

**Comment by francoishamon** [comment]
> @francoishamon @sytuannguyen @CusiniM @TotoGaz @herve-gross As requested, I've reran all the integratedTests with this PR on Pecan. Unfortunately, several unexpected fail runs are detected:
> 
> ```
>       Status     :  TestCase                                        :  Elapsed :  Resources :  TestStep     :  OutFile                                                                                                                     
>      ---------- :  ----------------------------------------------- :  ------- :  --------- :  ------------ :  ----------------------------------------------------------------------------------------------------------------------------
>      FAIL RUN   :  co2_thermal_obl_3d_01                           :  0:00:03 :  0:00:03   :  geosx        :  thermalMultiphaseFlow/co2_thermal_obl_3d_01/co2_thermal_obl_3d_01.data                                                      
>                 :                                                  :          :            :               :  thermalMultiphaseFlow/co2_thermal_obl_3d_01/co2_thermal_obl_3d_01.err                                                       
>      FAIL RUN   :  WillisRichardsPermeability_EDFM_01              :  0:00:02 :  0:00:02   :  geosx        :  poromechanicsFractures/WillisRichardsPermeability_EDFM_01/WillisRichardsPermeability_EDFM_01.data                           
>                 :                                                  :          :            :               :  poromechanicsFractures/WillisRichardsPermeability_EDFM_01/WillisRichardsPermeability_EDFM_01.err                            
>      FAIL RUN   :  PoroElastic_staircase_co2_3d_1-1-1              :  0:00:11 :  0:00:11   :  geosx        :  poroElasticCoupling/PoroElastic_staircase_co2_3d_1-1-1/PoroElastic_staircase_co2_3d_1-1-1.data                              
>                 :                                                  :          :            :               :  poroElasticCoupling/PoroElastic_staircase_co2_3d_1-1-1/PoroElastic_staircase_co2_3d_1-1-1.err                               
>      FAIL RUN   :  PoroElastic_deadoil_3ph_baker_2d1-1-1           :  0:00:02 :  0:00:02   :  geosx        :  poroElasticCoupling/PoroElastic_deadoil_3ph_baker_2d1-1-1/PoroElastic_deadoil_3ph_baker_2d1-1-1.data                        
>                 :                                                  :          :            :               :  poroElasticCoupling/PoroElastic_deadoil_3ph_baker_2d1-1-1/PoroElastic_deadoil_3ph_baker_2d1-1-1.err                         
>      FAIL RUN   :  Sneddon_smoke_01                                :  0:00:01 :  0:00:01   :  geosx        :  embeddedFractures/Sneddon_smoke_01/Sneddon_smoke_01.data embeddedFractures/Sneddon_smoke_01/Sneddon_smoke_01.err            
>      FAIL RUN   :  EmbFrac_Compression_Frictionless_01             :  0:00:01 :  0:00:01   :  geosx        :  embeddedFractures/EmbFrac_Compression_Frictionless_01/EmbFrac_Compression_Frictionless_01.data                              
>                 :                                                  :          :            :               :  embeddedFractures/EmbFrac_Compression_Frictionless_01/EmbFrac_Compression_Frictionless_01.err                               
>      FAIL RUN   :  EmbFrac_Compression_CoulombFriction_01          :  0:00:01 :  0:00:01   :  geosx        :  embeddedFractures/EmbFrac_Compression_CoulombFriction_01/EmbFrac_Compression_CoulombFriction_01.data                        
>                 :                                                  :          :            :               :  embeddedFractures/EmbFrac_Compression_CoulombFriction_01/EmbFrac_Compression_CoulombFriction_01.err                         
>      FAIL RUN   :  ContactMechanics_UnstructuredCrack_01           :  0:00:02 :  0:00:02   :  geosx        :  contactMechanics/ContactMechanics_UnstructuredCrack_01/ContactMechanics_UnstructuredCrack_01.data                           
>                 :                                                  :          :            :               :  contactMechanics/ContactMechanics_UnstructuredCrack_01/ContactMechanics_UnstructuredCrack_01.err                            
>      FAIL RUN   :  ContactMechanics_TFrac_01                       :  0:00:02 :  0:00:02   :  geosx        :  contactMechanics/ContactMechanics_TFrac_01/ContactMechanics_TFrac_01.data                                                   
>                 :                                                  :          :            :               :  contactMechanics/ContactMechanics_TFrac_01/ContactMechanics_TFrac_01.err                                                    
>      FAIL RUN   :  ContactMechanics_SingleFracCompression_01       :  0:00:08 :  0:00:08   :  geosx        :  contactMechanics/ContactMechanics_SingleFracCompression_01/ContactMechanics_SingleFracCompression_01.data                   
>                 :                                                  :          :            :               :  contactMechanics/ContactMechanics_SingleFracCompression_01/ContactMechanics_SingleFracCompression_01.err                    
>      FAIL RUN   :  dead_oil_wells_hybrid_2d_01                     :  0:00:07 :  0:00:07   :  geosx        :  compositionalMultiphaseWell/dead_oil_wells_hybrid_2d_01/dead_oil_wells_hybrid_2d_01.data                                    
>                 :                                                  :          :            :               :  compositionalMultiphaseWell/dead_oil_wells_hybrid_2d_01/dead_oil_wells_hybrid_2d_01.err                                     
>      FAIL RUN   :  isothermalLeakyWell_smoke_3d_01                 :  0:00:30 :  0:00:30   :  geosx        :  compositionalMultiphaseFlow/isothermalLeakyWell_smoke_3d_01/isothermalLeakyWell_smoke_3d_01.data                            
>                 :                                                  :          :            :               :  compositionalMultiphaseFlow/isothermalLeakyWell_smoke_3d_01/isothermalLeakyWell_smoke_3d_01.err                             
>      FAIL RUN   :  thermalLeakyWell_smoke_3d_01                    :  0:04:21 :  0:04:21   :  geosx        :  compositionalMultiphaseFlow/thermalLeakyWell_smoke_3d_01/thermalLeakyWell_smoke_3d_01.data                                  
>                 :                                                  :          :            :               :  compositionalMultiphaseFlow/thermalLeakyWell_smoke_3d_01/thermalLeakyWell_smoke_3d_01.err                                   
>      FAIL RUN   :  deadoil_2ph_staircase_gravity_segregation_3d_01 :  0:00:21 :  0:00:21   :  geosx        :  compositionalMultiphaseFlow/deadoil_2ph_staircase_gravity_segregation_3d_01/deadoil_2ph_staircase_gravity_segregation_3d_01.data
>                 :                                                  :          :            :               :  compositionalMultiphaseFlow/deadoil_2ph_staircase_gravity_segregation_3d_01/deadoil_2ph_staircase_gravity_segregation_3d_01.err
>      FAIL RUN   :  DryFrac_StaticPenny_PrismElem_01                :  0:00:11 :  0:00:11   :  geosx        :  SurfaceGenerator/DryFrac_StaticPenny_PrismElem_01/DryFrac_StaticPenny_PrismElem_01.data                                     
>                 :                                                  :          :            :               :  SurfaceGenerator/DryFrac_StaticPenny_PrismElem_01/DryFrac_StaticPenny_PrismElem_01.err                                      
>      FAIL RUN   :  kgdValidation_smoke_01                          :  0:00:02 :  0:00:02   :  geosx        :  HydrofracturingSolver/kgdValidation_smoke_01/kgdValidation_smoke_01.data                                                    
>                 :                                                  :          :            :               :  HydrofracturingSolver/kgdValidation_smoke_01/kgdValidation_smoke_01.err                                                     
>      FAIL RUN   :  heterogeneousInSitu_smoke_01                    :  0:00:11 :  0:00:11   :  geosx        :  HydrofracturingSolver/heterogeneousInSitu_smoke_01/heterogeneousInSitu_smoke_01.data                                        
>                 :                                                  :          :            :               :  HydrofracturingSolver/heterogeneousInSitu_smoke_01/heterogeneousInSitu_smoke_01.err                                         
>      FAIL RUN   :  pennyShapedToughnessDominated_smoke_01          :  0:00:05 :  0:00:05   :  geosx        :  HydrofracturingSolver/pennyShapedToughnessDominated_smoke_01/pennyShapedToughnessDominated_smoke_01.data                    
>                 :                                                  :          :            :               :  HydrofracturingSolver/pennyShapedToughnessDominated_smoke_01/pennyShapedToughnessDominated_smoke_01.err                     
>      FAIL RUN   :  pennyShapedViscosityDominated_smoke_01          :  0:00:06 :  0:00:06   :  geosx        :  HydrofracturingSolver/pennyShapedViscosityDominated_smoke_01/pennyShapedViscosityDominated_smoke_01.data                    
>                 :                                                  :          :            :               :  HydrofracturingSolver/pennyShapedViscosityDominated_smoke_01/pennyShapedViscosityDominated_smoke_01.err                     
>      FAIL RUN   :  pknViscosityDominated_smoke_01                  :  0:00:06 :  0:00:06   :  geosx        :  HydrofracturingSolver/pknViscosityDominated_smoke_01/pknViscosityDominated_smoke_01.data                                    
>                 :                                                  :          :            :               :  HydrofracturingSolver/pknViscosityDominated_smoke_01/pknViscosityDominated_smoke_01.err                                     
>      FAIL RUN   :  walshQuarter01                                  :  0:00:05 :  0:00:05   :  geosx        :  HydrofracturingSolver/walshQuarter01/walshQuarter01.data HydrofracturingSolver/walshQuarter01/walshQuarter01.err            
>      ---------- :  ----------------------------------------------- :  ------- :  --------- :  ------------ :  ----------------------------------------------------------------------------------------------------------------------------
>      FAIL CHECK :  hybridHexPrism_LaplaceVEM_smoke_01              :  0:00:03 :  0:00:03   :  restartcheck :  simplePDE/hybridHexPrism_LaplaceVEM_smoke_01/hybridHexPrism_LaplaceVEM_smoke_01.data                                        
>                 :                                                  :          :            :               :  simplePDE/hybridHexPrism_LaplaceVEM_smoke_01/hybridHexPrism_LaplaceVEM_smoke_01.err                                         
>      ---------- :  ----------------------------------------------- :  ------- :  --------- :  ------------ :  ----------------------------------------------------------------------------------------------------------------------------
> ```
> 
> By checking the .data files, various errors are reported:
> 
> for ContactMechanics_UnstructuredCrack (nan values for residual):
> 
> ```
> Time: 0s, dt:1s, Cycle: 0
>   Number of element for each fracture state: stick:          120 | slip:             0 | open:             0
>     Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
>     ( Rdisplacement, Rtraction, Rtotal ) = (    1.000000e+00,    1.000000e+00,    1.000000e+00 );
>     ( R ) = ( 1.00e+00 ) ; 
>     Attempt:  0, ConfigurationIter:  0, NewtonIter:  1
>     ( Rdisplacement, Rtraction, Rtotal ) = ( nan            , -nan           , nan             );
>     ( R ) = ( nan  ) ; 
>     Last LinSolve(iter,res) = (   1, -nan ) ; 
> ```
> 
> For co2_thermal_obl_3d (unconvergence):
> 
> ```
> New dt = 50000
>     Attempt:  1, ConfigurationIter:  0, NewtonIter:  0
>     ( Rflow ) = ( 1.23e+01 ) ;
>     ( R ) = ( 1.23e+01 ) ; 
>     Solution check failed. Newton loop terminated.
> New dt = 25000
> Convergence not achieved.
> ***** ERROR
> ***** LOCATION: /lustre4/scratch/j0551570/geosx/SyTuan/GEOSX/src/coreComponents/physicsSolvers/SolverBase.cpp:743
> ***** Controlling expression (should be false): true
> ***** Rank 0: Nonconverged solutions not allowed. Terminating...
> ```
> 
> For walshQuarter (just crashed at first step):
> 
> ```
> regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh1, Level0, void, void
> mesh1/Level0/void/void/water allocated 8 quadrature points
> mesh1/Level0/void/void/rock allocated 8 quadrature points
> Time: 0s, dt:0.0001s, Cycle: 0
>     Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
> singlePhaseTPFA
>     ( R ) = ( 8.30e-01 ) ; 
> 		Linear Solver | Success | Iterations: 1 | Final Rel Res: -nan | Setup Time: 2.75492 s | Solve Time: 0.0144221 s
> ```
> 
> I guess these issues/errors are not introduced by this PR.

Yes, you are right, these errors are not introduced by the PR, everything still works well with it on Quartz. We must have an issue with our configuration on Pecan, I am having a look

**Comment by francoishamon** [comment]
On Pecan, the problem takes place in the direct solver `Umfpack` with multi-threaded simulations. 

Precisely, here:
https://github.com/GEOSX/GEOSX/blob/5f81bd32e2eb6043d13e6005bf47d258402441a4/src/coreComponents/linearAlgebra/interfaces/direct/SuiteSparse.cpp#L314-L322
the Pecan input is correct (and the same as the Quartz input). But, for multithreaded simulations on Pecan,`Umfpack` fails to reduce the linear residual and so the simulation does not converge. The problem does not appear for single-thread simulations, and everything is fine with iterative linear solvers.

So @jhuang2601 while we figure out why `Umfpack` does not work anymore with multiple threads on Pecan, the workaround to run the integrated tests is to type:
```
export OMP_NUM_THREADS=1
```
before doing `./geosxats.sh`, and then all the integrated tests will pass.

**Review by jhuang2601 — APPROVED** [review]
Nice work.

**Pull request merged**
