### PR TITLE
Not using a specific hash for brew installation.

### LINKED ISSUE #1149: Mac build pattern won't work anymore with brew
As pointed by @af1990 in build https://travis-ci.com/github/GEOSX/GEOSX/jobs/382490297
There is something wrong with brew installing `open-mpi`.

PR https://github.com/Homebrew/brew/pull/8513 has disabled the functionality we were relying on (~installing old versions from an URL).
It's been deprecated since https://github.com/MikeMcQuaid/brew/commit/a35825ff230154fbab37c2ea936af4ebee65f186 (3 months), did not see it coming though.

There seems to be a new `brew extract` way imposed.
I quite don't get what they mean ; I'll give it a shot.
But I am not willing to spend to much time.

So If we cannot make it, I suggest that for the moment we give up this way of maintaining a specific version of `open-mpi`: let's rely on what `homebrew` wants. The result is that like the old days, from time to time we have to recompile the TPLs with the latest open-mpi.

Any comments?

### PR DESCRIPTION
**Pull request by TotoGaz**
The feature has been removed by homebrew itself.

Fixes #1149 

Related to PR https://github.com/GEOSX/thirdPartyLibs/pull/127

### CODE REVIEW

**Comment by TotoGaz** [comment]
This patch cancels all the tricks about `brew`; it's ready for merging.
@af1990 is trying another solution to keep our `brew` version selection.
In case it's not successful, we can merge the current PR.

**Comment by af1990** [comment]
I'm waiting for GEOSX/thirdPartyLibs#128. As soon as it's done, I'll let you know.

**Comment by af1990** [comment]
The pair GEOSX/thirdPartyLibs#128 and #1148 seems to work.

**Comment by af1990** [comment]
If we want rely always on the latest Open MPI, this solution works well.

**Review by af1990 — APPROVED** [review]

**Review by rrsettgast — APPROVED** [review]

**Comment by TotoGaz** [comment]
@rrsettgast Note that @af1990 is experimenting a promising way of keeping the `brew` trick.
It was working for `open-mpi` 4.0.2.
We need to test 4.0.5 to be sure (no need to use a new trick if we cannot update it).

If it fails, we have the complete removal as fallback.

**Comment by af1990** [comment]
With OpenMPI 4.0.5.

**Pull request closed without merging**
