### PR TITLE
LC TPLs rebuild after Ubuntu 22 Added to Travis CI

### PR DESCRIPTION
**Pull request by bmhan12**
This PR:

- Addresses #2103 

- [x] ~~TODO : Requires a rebaseline (`PoroImpermeableFault_smoke` and `PoropermeableFault_smoke` test failures)~~

Related to GEOSX/LvArray#272
Related to GEOSX/thirdPartyLibs#201
~~Related to GEOSX/integratedTests#268~~

### CODE REVIEW

**Comment by TotoGaz** [comment]
Did I do anything wrong?

**Comment by bmhan12** [comment]
> Did I do anything wrong?

No, I forgot to update the LC TPLs as part of the Trilinos upgrade.
Now the host-config changes will match the TPLs.

**Review by klevzoff — APPROVED** [review]

**Review by TotoGaz — APPROVED** [review]

**Comment by castelletto1** [comment]
Can we please merge this PR as soon as possible? I would move it in front of the merge queue. Thanks

**Comment by castelletto1** [comment]
> * [x]  TODO : Requires a rebaseline (`PoroImpermeableFault_smoke` and `PoropermeableFault_smoke` test failures)

Have you investigated the root cause behind the failed check for the tests above?

**Comment by jhuang2601** [comment]
> > * [x]   TODO : Requires a rebaseline (`PoroImpermeableFault_smoke` and `PoropermeableFault_smoke` test failures)
> 
> Have you investigated the root cause behind the failed check for the tests above?
> 
> (adding to the discussion @jhuang2601)

As far as I know, these two tests have not been updated recently and why rebaseline is required? 
Concur with @castelletto1 for the investigation of the unexpected failure.

**Comment by bmhan12** [comment]
> Concur with @castelletto1 for the investigation of unexpected failure.

I've attached a zipped folder with the debugging output (before rebasing):
[Debug Files.zip](https://github.com/GEOSX/GEOSX/files/9735507/Debug.Files.zip)

I am surprised a rebaseline was required... the only changes to the TPLs were upgraded versions of caliper and trilinos.

**Comment by jhuang2601** [comment]
> > Concur with @castelletto1 for the investigation of unexpected failure.
> 
> I've attached a zipped folder with the debugging output (before rebasing): [Debug Files.zip](https://github.com/GEOSX/GEOSX/files/9735507/Debug.Files.zip)
> 
> I am surprised a rebaseline was required... the only changes to the TPLs were upgraded versions of caliper and trilinos.

Thanks @bmhan12 
It looks like the failure is related to this [mesh](https://github.com/GEOSX/GEOSX/blob/develop/inputFiles/poromechanics/faultMesh_smoke.vtk) or the way how this vtk mesh been imported.

**Comment by CusiniM** [comment]
I think we should merge this to update the `LvArray` tag and deal with the `integratedTests` later.

**Comment by bmhan12** [comment]
`PoroImpermeableFault_smoke` and `PoropermeableFault_smoke` test are no longer failing after merging with develop. Closing associated integratedTests branch.

**Pull request merged**
