### PR TITLE
Update blt to v0.5.1

### PR DESCRIPTION
**Pull request by victorapm**
This PR fixes the numeric_limits error that I was getting when building GEOSX with clang-12, see
[clang12_errors.txt](https://github.com/GEOSX/GEOSX/files/8498060/clang12_errors.txt)

### CODE REVIEW

**Comment by rrsettgast** [comment]
Did anyone check if this causes problems on Lassen or Pangea3? @wrtobin What blt are you using for Crusher?

**Comment by wrtobin** [comment]
> Did anyone check if this causes problems on Lassen or Pangea3? @wrtobin What blt are you using for Crusher?

On crusher I'm using blt@0.5.0. 
0.5.1 shouldn't break anything since the big hip dependency change was in the 0.4.X => 0.5.0 release.

**Comment by victorapm** [comment]
@rrsettgast, I can check if this is fine on Lassen.

**Comment by victorapm** [comment]
I tested this PR with `lassen-clang@upstream` and `lassen-gcc@8.3.1` on Lassen and it worked fine.

**Review by rrsettgast — APPROVED** [review]

**Pull request merged**
