### PR TITLE
Adding method to import nodesets in vtk meshes, convert abaqus meshes to vtu

### PR DESCRIPTION
**Pull request by cssherman**

### CODE REVIEW

**Comment by cssherman** [comment]
I've tested the prototype methods implemented here on a couple of simple block meshes, which were converted from an abaqus format.  Qualitatively at least, it behaved as expected in serial and with 2x2x2 partitions.

**Comment by cssherman** [comment]
Also, I can confirm that the default compression in VTK does a good job of minimizing the size of nodeset masks

**Comment by cssherman** [comment]
@AntoineMazuyer @francoishamon - could you give this a look?  This would be useful to include in the new VTK documentation if you are on board with the approach

**Review by francoishamon — APPROVED** [review]
Sorry for the slow review, this looks good to me

**Comment by cssherman** [comment]
#1940

**Pull request merged**
