### PR TITLE
Removing plot level for a 4d field

### PR DESCRIPTION
**Pull request by af1990**
This is a one line PR to solve issue #1112.

### CODE REVIEW

**Comment by af1990** [comment]
I don't know, maybe there are better solutions, but ... how would it be possible to visualize a 4D array?

**Comment by francoishamon** [comment]
Yes I agree with you, it is always a little bit cumbersome to visualize this field.

Here is what Visit does to visualize the `phaseCompFraction` field in a finite-volume simulation. It discards the second dimension corresponding to the number of quadrature points, so for each element, you have `NP * NC` values to display. Visit lets you visualize a separate field for each possible pair (phase, component). So for instance for a CO2 simulation (`NP = 2` and `NC = 2`), you can click on the following fields: `phaseCompFraction_0_0`, `phaseCompFraction_0_1`, `phaseCompFraction_1_0`, `phaseCompFraction_1_1`. For more phases/components, it quickly becomes very messy.

**Comment by AntoineMazuyer** [comment]
It's strange that default behavior is not NOPLOT...

**Review by AntoineMazuyer — APPROVED** [review]

**Comment by af1990** [comment]
> 
> 
> It's strange that default behavior is not NOPLOT...

The default is `NOPLOT`. The problem with `phaseCompFraction` is that the plot level was set to `LEVEL_0`.

**Comment by rrsettgast** [comment]
> It's strange that default behavior is not NOPLOT...

If it wasn't, then you would plot everything unless you stated otherwise.

**Comment by rrsettgast** [comment]
> Yes I agree with you, it is always a little bit cumbersome to visualize this field.
> 
> Here is what Visit does to visualize the `phaseCompFraction` field in a finite-volume simulation. It discards the second dimension corresponding to the number of quadrature points, so for each element, you have `NP * NC` values to display. Visit lets you visualize a separate field for each possible pair (phase, component). So for instance for a CO2 simulation (`NP = 2` and `NC = 2`), you can click on the following fields: `phaseCompFraction_0_0`, `phaseCompFraction_0_1`, `phaseCompFraction_1_0`, `phaseCompFraction_1_1`. For more phases/components, it quickly becomes very messy.

But don't you want to plot this data?

**Comment by francoishamon** [comment]
> > Yes I agree with you, it is always a little bit cumbersome to visualize this field.
> > Here is what Visit does to visualize the `phaseCompFraction` field in a finite-volume simulation. It discards the second dimension corresponding to the number of quadrature points, so for each element, you have `NP * NC` values to display. Visit lets you visualize a separate field for each possible pair (phase, component). So for instance for a CO2 simulation (`NP = 2` and `NC = 2`), you can click on the following fields: `phaseCompFraction_0_0`, `phaseCompFraction_0_1`, `phaseCompFraction_1_0`, `phaseCompFraction_1_1`. For more phases/components, it quickly becomes very messy.
> 
> But don't you want to plot this data?

Yes, sorry for being unclear. I think we want to plot this data, even if it is cumbersome. It can be important to understand what is going on in the simulation. The phase component fraction is a primary variable in the natural variable formulation used by some compositional simulators, so people would expect this variable to be plotted, I think. 

I think the way this variable is currently plotted with Silo/Visit (described above) is working well, and that would be great to have the same option available with VTK/Paraview, but I don't realize how much work it is to make it work. The fix that @af1990  proposes could be a temporary solution to have the tutorials running while we work of the VTK output for `array4d`. @AntoineMazuyer what do you think about this?

**Pull request merged**
