### PR TITLE
Fixed bug linking to system tpls.

### PR DESCRIPTION
**Pull request by corbett5**

### CODE REVIEW

**Review by rrsettgast — APPROVED** [review]

**Comment by TotoGaz** [comment]
@corbett5 I'd like to test it against https://github.com/GEOSX/thirdPartyLibs/pull/142 
We could include the code (commented), that could be a nice test when deep modifications in the build system are made.

**Comment by corbett5** [comment]
@TotoGaz I'm not sure what you mean _include the code (commented)_, this doesn't prohibit you from using system libraries, but if you want to use them you'll have to hard-code the path, which seems pretty reasonable to me. Either way would you like me to hold off merging this until you're ready (until you approve this PR)?

**Comment by TotoGaz** [comment]
I mean it could be interesting to effectively validate our script against all the system libs that are in ubuntu (e.g.). There may be some libs we have forgotten.
Furthermore, from time to time when we move our build system, uncommenting the code installing all the system libs could save us time.

**Comment by corbett5** [comment]
Ahhh. Have you checked that the versions we use all have packages?

**Pull request merged**
