### PR TITLE
Quick tutorial on time series

### PR DESCRIPTION
**Pull request by herve-gross**
This is very brief, but it may be useful. Not sure this should be in the tutorials though. A "how to" section?

### CODE REVIEW

**Comment by joshua-white** [comment]
@herve-gross, I agree, I suggest we add this in the User Guide somewhere, rather than as a tutorial.

**Comment by rrsettgast** [comment]
@wrtobin Can you have a look at this and make any corrections that are required?

**Comment by joshua-white** [comment]
I'd suggest we also restructure this as just a regular User Guide entry, rather than a Tutorial.  It can still be written "mostly" like a Tutorial, but maybe with a bit more comprehensive info.

**Comment by rrsettgast** [comment]
@joshua-white @wrtobin Should this be merged?

**Pull request closed without merging**
