### PR TITLE
Fix non conformal mesh drawing in doc

### PR DESCRIPTION
**Pull request by TotoGaz**
Remove `msh` hint.
Improve english.

### CODE REVIEW

**Comment by castelletto1** [comment]
In [Supported Formats](https://github.com/GEOSX/GEOSX/blob/8681189cdebeea831d654ce101c219523f408730/src/coreComponents/mesh/docs/Mesh.rst#supported-formats)

```suggestion
4-node tetrahedra,
5-node pyramids,
6-node wedges,
8-node hexahedra,
n-gonal prisms (n = 7, ..., 11).
```

**Comment by castelletto1** [comment]
Check this. I believe with `vtk` we need to use the region attribute field (at the moment).

```
The ElementRegions are defined as below :

<ElementRegions>
  <ElementRegion
    name="Top"
    cellBlocks="Top_hexahedra Top_wedges Top_tetrahedra"
    materialList="water rock"/>
  <ElementRegion
    name="Bot"
    cellBlocks="Bot_hexahedra Bot_wedges Bot_tetrahedra"
    materialList="water rock"/>
</ElementRegions>
```

**Comment by castelletto1** [comment]
Do we still need [toy_model.GRDECL](https://github.com/GEOSX/GEOSX/blob/8681189cdebeea831d654ce101c219523f408730/src/coreComponents/unitTests/meshTests/toy_model.GRDECL) and [toy_model.msh](https://github.com/GEOSX/GEOSX/blob/8681189cdebeea831d654ce101c219523f408730/src/coreComponents/unitTests/meshTests/toy_model.msh)?

**Review by castelletto1 — APPROVED** [review]

**Comment by TotoGaz** [comment]
> Do we still need [toy_model.GRDECL](https://github.com/GEOSX/GEOSX/blob/8681189cdebeea831d654ce101c219523f408730/src/coreComponents/unitTests/meshTests/toy_model.GRDECL) and [toy_model.msh](https://github.com/GEOSX/GEOSX/blob/8681189cdebeea831d654ce101c219523f408730/src/coreComponents/unitTests/meshTests/toy_model.msh)?

Could they be useful for future conversions and test cases. I can remove them id needed.

**Comment by castelletto1** [comment]
> > Do we still need [toy_model.GRDECL](https://github.com/GEOSX/GEOSX/blob/8681189cdebeea831d654ce101c219523f408730/src/coreComponents/unitTests/meshTests/toy_model.GRDECL) and [toy_model.msh](https://github.com/GEOSX/GEOSX/blob/8681189cdebeea831d654ce101c219523f408730/src/coreComponents/unitTests/meshTests/toy_model.msh)?
> 
> Could they be useful for future conversions and test cases. I can remove them id needed.

OK, let's keep them.

**Pull request merged**
