### PR TITLE
Updating sphinx publications

### PR DESCRIPTION
**Pull request by jhuang2601**
Add a recent publication on proppant transport model to the publications list

### CODE REVIEW

**Review by castelletto1 — CHANGES_REQUESTED** [review]
- Please order papers by first author family name. Note also Lee et al. is misplaced. 
- Could you please update Tang et al. (currently listed as a preprint)? Here's the [link](https://www.sciencedirect.com/science/article/pii/S1750583622001839) to the published version.

**Comment by jhuang2601** [comment]
> * Please order papers by first author family name. Note also Lee et al. is misplaced.
> * Could you please update Tang et al. (currently listed as a preprint)? Here's the [link](https://www.sciencedirect.com/science/article/pii/S1750583622001839) to the published version.

Thanks for your review and these changes have been applied.

**Review by castelletto1 — APPROVED** [review]
Could you please also add the following publication to the preprints 
```
   * - | **A Multi-Resolution Approach to Hydraulic Fracture Simulation**
       | A Costa, M Cusini, T Jin, R Settgast, J Dolbow
       | arXiv preprint
       | `arXiv:2207.00661 <https://arxiv.org/abs/2207.00661>`_
```

and close PR #1985? Thank you!

**Comment by jhuang2601** [comment]
> Could you please also add the following publication to the preprints
> 
> ```
>    * - | **A Multi-Resolution Approach to Hydraulic Fracture Simulation**
>        | A Costa, M Cusini, T Jin, R Settgast, J Dolbow
>        | arXiv preprint
>        | `arXiv:2207.00661 <https://arxiv.org/abs/2207.00661>`_
> ```
> 
> and close PR #1985? Thank you!

Sure, done

**Review by rrsettgast — APPROVED** [review]

**Pull request merged**
