### PR TITLE
Improve logs when product is not found in catalog.

### PR DESCRIPTION
**Pull request by TotoGaz**
The user will receive a more comprehensive message in case of typo or error in the input file.

Another example of issue https://github.com/GEOSX/GEOSX/issues/705

### CODE REVIEW

**Review by joshua-white — APPROVED** [review]
I think this will be super useful.

**Review by herve-gross — APPROVED** [review]
Nice! A good way to catch XML errors, with good guidance on how to correct these issues.

**Comment by TotoGaz** [comment]
@rrsettgast do you want to merge your `string` PR first?

**Comment by TotoGaz** [comment]
> A good way to catch XML errors

Actually I thought we already had something like this...

> I think this will be super useful.

It may save hours and hours.

**Review by rrsettgast — APPROVED** [review]
@TotoGaz Can you show the error message as it is printed out in the case of an incorrect key lookup?

**Comment by TotoGaz** [comment]
> @TotoGaz Can you show the error message as it is printed out in the case of an incorrect key lookup?

It displays this
```
***** ERROR
***** LOCATION: ../coreComponents/dataRepository/ObjectCatalog.hpp:190
***** Controlling expression (should be false): true
***** Rank 0: Could not find "Banana" in this catalog. Please be sure that all your keywords are properly spelled or that input file parameters have not changed.
All available keys are: [
Dirichlet,
FieldSpecification,
SourceFlux
]
```
or 
```
***** ERROR
***** LOCATION: ../coreComponents/dataRepository/ObjectCatalog.hpp:190
***** Controlling expression (should be false): true
***** Rank 0: Could not find "Banana" in this catalog. Please be sure that all your keywords are properly spelled or that input file parameters have not changed.
All available keys are: [
HaltEvent,
PeriodicEvent,
SoloEvent
]
```

**Comment by rrsettgast** [comment]
@TotoGaz This looks great to me...but my only concerns are:
1.  whether a user should know what a "Catalog" is.
2. the dependency between `ObjectCatalog.hpp` and `StringUtilites.hpp`. More to the point the circular dependency that is being introduced between `dataRepository` and `codingUtilites`?

**Comment by TotoGaz** [comment]
> 1. whether a user should know what a "Catalog" is. Perhaps add a message indicating that the incorrect keyword is specified in their input file?

I wanted to emphasize that an invalid keyword could be OK in other context.
As per using the catalog word, it's already in the error message just above.
I could say `Could not find keyword "Banana" for this context.`?

> 2. the dependency between `ObjectCatalog.hpp` and `StringUtilites.hpp`. More to the point the circular dependency that is being introduced between `dataRepository` and `codingUtilites`?

That could be troublesome indeed.
But code like `StringUtilites.hpp` in `codingUtilites` are more low-level utility c++ coding helpers.
Why would should such code depend on `dataRepository`?
How could a circular dependency _legitimately_ occur?

**Comment by rrsettgast** [comment]
> > 1. whether a user should know what a "Catalog" is. Perhaps add a message indicating that the incorrect keyword is specified in their input file?
> 
> I wanted to emphasize that an invalid keyword could be OK in other context.
> As per using the catalog word, it's already in the error message just above.
> I could say `Could not find keyword "Banana" for this context.`?
> 
I am just emphasizing that user doesn't know what a "Catalog" is. We could just indicate that there could be an incorrect keyword in their input file in addition to the message.


> > 1. the dependency between `ObjectCatalog.hpp` and `StringUtilites.hpp`. More to the point the circular dependency that is being introduced between `dataRepository` and `codingUtilites`?
> 
> That could be troublesome indeed.
> But code like `StringUtilites.hpp` in `codingUtilites` are more low-level utility c++ coding helpers.
> Why would should such code depend on `dataRepository`?
> How could a circular dependency _legitimately_ occur?

I am mistaken. I was interrupted while reviewing and got crossed up.

**Comment by TotoGaz** [comment]
@rrsettgast is the error message OK ?
`Could not find keyword "Banana" in this context.` and `"Banana" could be found. But the builder is invalid.`

**Comment by TotoGaz** [comment]
yes of course ;)

**Pull request merged**
