### PR TITLE
Update submodule BLT to v0.3.6

### PR DESCRIPTION
**Pull request by TotoGaz**

### CODE REVIEW

**Comment by corbett5** [comment]
@TotoGaz can you update BLT in LvArray, PAMELA, and PVT too? I know that's three additional PRs but I think it's for the best.

**Comment by TotoGaz** [comment]
Do I have to do it all at one or can I do it with the flow?

**Comment by corbett5** [comment]
It's honestly probably easiest to do it all at once since each one would require a PR in GEOSX. Add me in each PR and I'll approve them ASAP.

**Comment by TotoGaz** [comment]
@corbett5 can you approve, I'm ready to merge 😝

**Review by corbett5 — APPROVED** [review]
Sorry for the delay, thanks a bunch!

**Pull request merged**
