### PR TITLE
Elastic Orthotropic constitutive model

### PR DESCRIPTION
**Pull request by sytuannguyen**
The Elastic Orthotropic constitutive model is important for many applications. For example sandstone or fractured rock mass ( that are sensitive to stress state in the earth crust which is orthotropic) can exhibit significant orthotropic anisotropy. However, this constitutive solver is not implemented yet. Using the existing fully anisotropic model for this problem is not optimal because we need to deal with 36 parameters in place of 9 parameters.

This PR aims to fill this gap. We can define either nine engineering elastic constants obtained from triaxial tests (i.e. E1, E2, E3, nu12, etc.) or nine independent elastic stiffnesses c11, c22, ... that can be computed directly from anisotropic sonic velocities (and density).

This PR include also some corrections of the ElasticIsotropic and ElasticTransverseIsotropic classes that are initially addressed in the PRs #1320 and #1321

Rebaseline PR: https://github.com/GEOSX/integratedTests/pull/148

### CODE REVIEW

**Comment by joshua-white** [comment]
@sytuannguyen, this seems very useful.  can you get it caught up to develop, passing checks, and in a state to merge?

**Comment by sytuannguyen** [comment]
@joshua-white After uncrustify as you suggested, now it passes. Please take a look.

**Review by joshua-white — APPROVED** [review]
Hey @sytuannguyen, this looks good.  Do you pass all the integrated tests?  What platforms have you tested on?  Will this require rebaselining the integrated tests?

**Comment by sytuannguyen** [comment]
@joshua-white I verified that the xml that is modified was not included in the integratedTests. So rebaseline the integratedTests is not required.

**Comment by rrsettgast** [comment]
@joshua-white Can you merge this if it fits in your plan?

**Pull request merged**
